package com.banyuan.gui1.ui;


import com.banyuan.gui1.StudentMenu;
import com.banyuan.gui1.dao.UserDao;
import com.banyuan.gui1.dao.impl.UserDaoImpl;
import com.banyuan.gui1.pojo.Admin;
import com.banyuan.gui1.pojo.Student;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;


//这是客户端

public class Login extends JFrame {

    public  static   ObjectOutputStream oos = null;
    public static    ObjectInputStream ois = null;
    private static   Socket  s=null;

    static{

        try {
            s=new Socket("192.168.11.22", 9090);
            oos=new ObjectOutputStream(s.getOutputStream());
            ois=new ObjectInputStream(s.getInputStream());
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    /**
     * Creates new form Login
     */

    private int result = 0;
    private UserDao userdao;
    private BJPanel  bjPanel;
    private Container  container;
    // Variables declaration - do not modify
    private JButton jButton1;
    private JButton jButton2;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JRadioButton jRadioButton1;
    private JRadioButton jRadioButton2;
    private JTextField jTextField1;
    private JTextField jTextField2;
    private ButtonGroup buttonGroup;

    public Login() {


        initComponents();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
      //  this.getContentPane().setBackground(Color.cyan);  设置背景色
       //设置背景图

        jLabel1 = new JLabel();

        System.out.println("进来没");
        jTextField1 = new JTextField();
        jTextField2 = new JTextField();
        jLabel2 = new JLabel();
        jButton1 = new JButton();
        jButton2 = new JButton();
        jRadioButton1 = new JRadioButton();
        jRadioButton2 = new JRadioButton();
        buttonGroup = new ButtonGroup();  // 添加按钮组  用来控制单选
        buttonGroup.add(jRadioButton1);
        buttonGroup.add(jRadioButton2);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("    账户：");

        jTextField2.addActionListener(new ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel2.setText("    密码：");

        jButton1.setText("登录");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("注册");
        jButton2.addActionListener(new ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jRadioButton1.setText("教师");
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseClicked(evt);
            }
        });

        jRadioButton2.setText("学生");
        jRadioButton2.setActionCommand("学生");
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton2MouseClicked(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(59, 59, 59)
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 62, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jTextField1, GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                                        .addComponent(jTextField2)))
                                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addContainerGap(122, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(jRadioButton1)
                                                                .addGap(29, 29, 29))
                                                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(jButton1)
                                                                .addGap(18, 18, 18)))
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addComponent(jButton2)
                                                        .addComponent(jRadioButton2, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE))))
                                .addGap(110, 110, 110))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
                                                .addGap(17, 17, 17))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextField2, GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jRadioButton1)
                                        .addComponent(jRadioButton2))
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton1)
                                        .addComponent(jButton2))
                                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {

        System.out.println(jTextField1.getText() + jTextField2.getText());

        //鼠标点击进入其他界面   跳转到其他界面其实就是重新创建一个框架   Jframe 或者 面板...

        String str = jTextField1.getText();  //获取账户名
        String pwd = jTextField2.getText();  //获取密码


        if (str == null || str.equals("")) {
            JOptionPane.showMessageDialog(this, "帐号不可为空", "Caution", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        if (pwd == null || pwd.equals("")) {
            JOptionPane.showMessageDialog(this, "密码不可为空", "Caution", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (result == 1) {
            //boolean flag = userdao.queryByNameAndByPwd(str, pwd);
            String   st=null;
            try {
                //把数据传到  服务器  再获取服务器返回的消息 进行判断 创建新的功能窗口
                Admin   admin=new Admin(str,pwd);
                oos.writeObject(admin);
                oos.flush();

//            Object   obj=    ois.readObject();
//                Admin      ad=null;
//            if(obj  instanceof   Admin){  // 判断是否是一个  指定的对象
//                ad=(Admin)obj;
//                System.out.println("从服务器端就收数据成功...");
//
//            }

              st = ois.readUTF();  //字符串型的  true 或者false

                System.out.println(">>>>>>>>>>>>"+st);

            } catch (Exception e) {
                e.printStackTrace();
            }

            if (st.equals("true")) {
                JOptionPane.showMessageDialog(this, "帐号和密码都正确,欢迎" + str+ "登录", "Caution", JOptionPane.WARNING_MESSAGE);
                Teacher t = new Teacher();
                t.setVisible(true);  //打开一个新的窗体对象
                this.setVisible(false); //关闭当前的窗口对象

            } else {
                JOptionPane.showMessageDialog(this, "帐号或者密码都不正确,请重新输入....", "Cal", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        String  st=null;

        if (result == 2) {
            Student  student=new Student();
            student.setSname(str);
            student.setSpwd(pwd);
            student.setFlag("stulogin");

            try {

                oos.writeObject(student);
                oos.flush();


                st=ois.readUTF();
                System.out.println("------"+st);

            } catch (IOException e) {
                e.printStackTrace();
            }

            if (st.equals("true")) {
                JOptionPane.showMessageDialog(this, "帐号和密码都正确,欢迎"+str+"登录", "Caution", JOptionPane.WARNING_MESSAGE);
                StudentMenu t = new StudentMenu();
                t.setVisible(true);  //打开一个新的窗体对象
                this.setVisible(false); //关闭当前的窗口对象
            } else {
                JOptionPane.showMessageDialog(this, "帐号或者密码都不正确,请重新输入....", "Cal", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
    }

    private void jRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {

        if (jRadioButton1.isSelected()) {
            result = 1;
        }

    }

    private void jRadioButton2MouseClicked(java.awt.event.MouseEvent evt) {
        if (jRadioButton2.isSelected()) {
            result = 2;
        }
    }



}
